# Generated by Django 4.1 on 2022-08-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0017_alter_solicitudtrabajo_usuario_a_vincular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajo',
            name='descripcion',
            field=models.TextField(default='', max_length=5000, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
